### ISSUE TITLE
[BUG] Cannot upvote or downvote

### ISSUE THREAD

**Issue by allywilson** [Athlon007/Leomard#11]
**Describe the bug**
Upvote/downvote buttons do not work

**To Reproduce**
1. Click on the up or down arrows at the bottom of a post.

**Expected behavior**
Expect the buttons to light up blue or orange to indicate it has upvoted/downvoted.

**Information:**
 - OS Version: Ventura 13.4.1 (c)

**Comment by Athlon007** [comment]
This is gonna sound silly, but did you try to press **precisely** on the upvote arrow? I know that the hitbox right now is very finicky.

**Comment by allywilson** [comment]
I did yeah. Took a quick video (sorry for the size, had to get it under 10Mb).

https://github.com/Athlon007/Leomard/assets/470127/e97ae71b-75a7-432e-8ac2-14aee3f4d1c5

**Comment by allywilson** [comment]
huh, it's like I am and I am not? 
I can see my message replies under Inbox, but if I press the Profile button in the bottom left it asks me to login again, and looking at the feed, it's not  my normal feed.

**Comment by Athlon007** [comment]
Ok, so the issue seems to be with authentication, it seems to me like Leomard hasn't been granted full access to Keychain...

You could try fixing it by doing the following:
1. Open 'Keychain Access' app
2. Select 'login' from left bar
3. In the search field type 'LeomardApp'
4. Remove the 'LeomardApp' entry

You will have to log back in.

**Comment by allywilson** [comment]
Done that, still the same I'm afraid.

**Comment by Athlon007** [comment]
With the changes done in 0.2, this _should_ be fixed. However, I am gonna keep it open for a while and add it to "Testing" column in the project.

**Comment by Athlon007** [comment]
Seems like the issue has been solved. Closing.
