### ISSUE TITLE
[BUG] Not all comments seem to always load

### ISSUE THREAD

**Issue by Athlon007** [Athlon007/Leomard#15]
**Describe the bug**
It seems like some comments never get loaded when opening a post.

**Expected behavior**
All comments should be visible.

**Comment by boscojwho** [comment]
API requests might be missing a `type_` parameter:
- Comments load if we pass `type_=All`.
- For example: The following request returns zero comments if we don't specify `type_=All` -> GET https://lemmy.world/api/v3/comment/list?post_id=1719940&sort=Top&page=1&auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjU1MTU4LCJpc3MiOiJsZW1teS53b3JsZCIsImlhdCI6MTY4OTcxMzE2NX0.gQf0aT0gg-dezBnpc2msE2BQsqQzuJ9h5wmD1cDVSCk&type_=All`

**Comment by boscojwho** [comment]
Relevant API doc: [https://join-lemmy.org/api/types/ListingType.html]()

**Comment by boscojwho** [comment]
CommentService gets all comments, but it currently filters out comments, so child comments don't get rendered after being downloaded.

**Comment by Athlon007** [comment]
Should be fixed in #82
