### ISSUE TITLE
[DEV] Refactor View body into separate @ViewBuilder var/func

### ISSUE THREAD

**Issue by boscojwho** [Athlon007/Leomard#20]
Will limit the scope of this issue to these top-level views:
- [x] ContentView
- [x] NavbarView
- [x] FeedView
- [x] LoginView
- [x] ProfileView
- [x] CommunityUIView
- [x] SearchView
- [x] PreferenceView
- [x] InboxView

Currently, many views have complicated subview trees (multiple nested views, complex if/else statements, difficult to read what view a view modifier is modifying, etc.)

We can get some quick wins for current/future contributors by refactoring subviews into separate, private view builders.

Doing so would improve readability and allow for more rapid iteration in the future.

**Comment by Athlon007** [comment]
Seems to be done! Thanks a lot for your help :) Closing.
