### ISSUE TITLE
[BUG] Post images reload when cell reappears after scrolled off-screen

### ISSUE THREAD

**Issue by boscojwho** [Athlon007/Leomard#30]
**Describe the bug**
After a post view loads an image, and user scrolls it out of view, the post view will reload that image when that post view's cell reappears.
- Not sure if post view is simply redrawing its state from loading to loaded (i.e. not actually redownloading the image).
- When this happens post view's height will shrink (and show a loading indicator), then expand, which is not ideal.

**To Reproduce**
1. Launch app to Feed list view.
2. Wait for First post image to load.
3. Scroll down so first post is just out of view.
4. Scroll back to top.
5. First post's image will reload.

**Expected behavior**
- Image should stay loaded, unless app receives memory warning, in which case post view still shouldn't be recalculating its height.

**Information:**
Version 0.1 (1)

**Comment by Athlon007** [comment]
I know of this issue, this is why there is this hacky workaround that retains the height of an image. From what I gathered, it has something to do with LazyVStack and AsyncImage combo. 

One solution would likely be switching to normal VStack. This will cost some memory, buuuuut that will fix issues with retention of height and images themselves.

**Comment by boscojwho** [comment]
> I know of this issue, this is why there is this hacky workaround that retains the height of an image. From what I gathered, it has something to do with LazyVStack and AsyncImage combo.

Indeed: [Found this post](https://stackoverflow.com/questions/69367132/using-vstack-with-asyncimage-inside-lazyvstack-causes-images-to-reload-on-scroll) here with the exact same issue.
- I set a value on URLCache.memoryCapacity/diskCapacity, removed the VStack from one of the AsyncImage instances in PostUIView and it fixed the caching issue.

**Comment by boscojwho** [comment]
> One solution would likely be switching to normal VStack. This will cost some memory, buuuuut that will fix issues with retention of height and images themselves.

I noticed the root view is a LazyVStack, which doesn't actually reuse cells after they are created, so it'll literally keep all post views in memory once they're created.
- We probably should be using `List` instead, which properly supports cell reuse.

**Comment by Athlon007** [comment]
Fixed in #33
