### ISSUE TITLE
[BUG] Unable to log in to accounts with 2FA enabled

### ISSUE THREAD

**Issue by gabedhughes** [Athlon007/Leomard#42]
**Describe the bug**
When attempting to log in to any Lemmy account with 2FA enabled, the app gives an error that states "Unable to login. Check your login info and try again."

**To Reproduce**
1. Enable 2FA on any Lemmy account
2. Attempt to log in using app
3. Attempted with multiple accounts
4. Verified ability to log in to accounts via the web

**Expected behavior**
App should request a 2 factor code from the user.

**Screenshots**
![leomard](https://github.com/Athlon007/Leomard/assets/29304194/99b3acb3-119b-41f8-b928-6693f0376dde)

**Information:**
 - OS Version: 14.0

**Additional context**

**Comment by Athlon007** [comment]
That's odd, I have the 2FA enabled too and it does work for me... I'll make the 2FA field permanent in the next version.

**Comment by Athlon007** [comment]
Fixed in #44
