### ISSUE TITLE
[BUG] Duplicate call to updateUnreadMessagesCount() in ContentView

### ISSUE THREAD

**Issue by boscojwho** [Athlon007/Leomard#54]
**Describe the bug**
We're calling into updateUnreadMessagesCount() twice, inside `.success` and at the end of `loadUserData()`. Not sure if this is intentional or a duplicate call. This is causing us to hit the unread count API twice on app launch.
(see lines 259/267)

**Screenshots**
<img width="756" alt="Screenshot 2023-07-23 at 3 46 06 PM" src="https://github.com/Athlon007/Leomard/assets/2549615/af762c36-dfd2-441f-bf40-345b9a16d423">

**Comment by Athlon007** [comment]
Should be easy to fix, thanks for that!

**Comment by Athlon007** [comment]
Addressed in #70
