### ISSUE TITLE
[FEATURE] Cross-post

### ISSUE THREAD

**Issue by vintprox** [Athlon007/Leomard#8]
Quite a common feature in Lemmy web interface (and outside) - cross-posting. What it basically does is clone the contents of a post, including:

- URL
- title
- description

Then, all this data is inserted in "Create Post" view. There, user can choose a community to which they wish to publish. What it essentially does is **duplicate** the contents of the post, to maybe slightly change the title or description or retain all the same.

The most common implementation (`lemmy-ui`) does exactly that, except that it prepends Markdown quote to each line of the original description. I did not research as to how useful it is, but it doesn't really help when you try cross-post your own content. As such, I think it is necessary to make it a default implementation to avoid mangling the description by simply copying it "as is".

An option to surround description in quote and add an inscription `cross-posted from https://original/post/url` should go into a separate issue. This one would be the most preferential for post made by another author, unlike your own where copyright is already assumed.

**Comment by Athlon007** [comment]
Definitely something that must be added.
